# using the lastest version of Ubuntu 22.04 as a base for the Docker image
FROM ubuntu:22.04

# installing Python and Unzip
RUN apt-get update && apt-get install -y python3.10 python3.10-venv python3.10-dev python3-pip libgomp1

# creating the root folder
RUN mkdir -p /e2e-project/notebooks

# copying all the files within this folder to the newly created folder
COPY /notebooks /e2e-project/notebooks/

# setting the curreting directory to be the folder containing the notebooks
WORKDIR /e2e-project

# updating pip
RUN pip install --no-cache-dir -U pip

# installing requirements
RUN pip install -r notebooks/requirements_dev.txt
